### ISSUE TITLE
no scroll bar for big playlist lists

### ISSUE THREAD

**Issue by Goten87** [SyndiShanX/Spotify-Dark#3] opened 2022-12-26 14:57 UTC
i have the left side with all my playlists and i dont get a scrollbar for that frame so i cant see all my playlists exept if i go to like fullscreen

**Comment by SyndiShanX** [comment] 2022-12-27 03:01
The theme shouldn't cause that

**Comment by Goten87** [comment] 2022-12-27 10:54
but if i disable the theme its back again
i isntalled it true the marketplace btw

**Comment by Goten87** [comment] 2022-12-27 12:59
just tryed a other theme and that has a scroll bar for the playlist frame

**Comment by SyndiShanX** [comment] 2022-12-27 14:46
Oh, I thought this was my Discord Theme, I’ll check it out in a bit

**Comment by SyndiShanX** [comment] 2022-12-27 15:12
I need a screenshot, I don't know fully what the issue is and I can't replicate it

**Comment by Goten87** [comment] 2022-12-27 15:27
I will sent it when I’m back on my pc standby please

**Comment by Goten87** [comment] 2022-12-27 16:25
![image](https://user-images.githubusercontent.com/1938598/209693928-4a403737-85e0-4118-949c-a1e27f1e92b3.png)

**Comment by Goten87** [comment] 2022-12-27 16:25
no scroll bar to go down

**Comment by SyndiShanX** [comment] 2022-12-27 16:26
Can you screenshot the whole screen?
That little part doesn't really help

**Comment by Goten87** [comment] 2022-12-27 16:26
![image](https://user-images.githubusercontent.com/1938598/209694138-2056ca68-8462-46c5-af07-aca49d99e5ef.png)

**Comment by Goten87** [comment] 2022-12-27 16:27
dont want to share my name so i cut it at the top

**Comment by Goten87** [comment] 2022-12-27 16:27
sec

**Comment by Goten87** [comment] 2022-12-27 16:28
![image](https://user-images.githubusercontent.com/1938598/209694304-e845e0f7-d78c-472f-b3ee-432f6e867ab3.png)

**Comment by Goten87** [comment] 2022-12-27 16:31
there is one extra playlist under castlefest winter edition
but even if i make the height less it will still not give me the scrollbar

**Comment by SyndiShanX** [comment] 2022-12-27 16:32
I can't get the playlist scrollbar to go away, but I have seen the issue with the sidebar covering the last one, so I'll look into that

**Comment by Goten87** [comment] 2022-12-27 16:35
This is a other theme and there i have again a scrollbar
![image](https://user-images.githubusercontent.com/1938598/209695034-2af8c771-7567-4c8e-b314-49479d9752cb.png)

**Comment by Goten87** [comment] 2022-12-27 16:35
oke went back to your theme and now i have a scroll bar O.o

**Comment by Goten87** [comment] 2022-12-27 16:36
ok nvm now its gone again

**Comment by Goten87** [comment] 2022-12-27 16:37
ok did some more testing for ya its not showing if only 1 playlist is hidden the scroll bar shows up when i make the screen smaller and castlefest will go away as well

**Comment by Goten87** [comment] 2022-12-27 16:39
when i scroll down with the scrollbar i will not see my last playlist still

**Comment by SyndiShanX** [comment] 2022-12-27 16:46
Pushed a fix, the theme should update in around 10 mins or so
Thanks for reporting this

**Closed as completed by SyndiShanX** 2022-12-27 16:46 UTC
